name: Deploy to Production via FTP

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      confirm_deployment:
        description: 'Type "deploy" to confirm production deployment'
        required: true
        default: 'deploy'

jobs:
  deploy-ftp:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch' && github.event.inputs.confirm_deployment == 'deploy' || github.event_name == 'push'

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Test FTP connection
      run: |
        echo "Testing FTP connection..."
        echo "Server: ${{ secrets.FTPSERVER }}"
        echo "Port: ${{ secrets.FTPPORT }}"
        echo "Username: ${{ secrets.USERFTP }}"
        echo "Remote dir: ${{ secrets.FTP_REMOTE_DIR }}"
        # Test basic FTP connection
        timeout 10 bash -c "</dev/tcp/${{ secrets.FTPSERVER }}/${{ secrets.FTPPORT }}" && echo "✅ Port is open" || echo "❌ Port is closed or unreachable"

    - name: Deploy via LFTP (alternative FTP client)
      run: |
        echo "Deploying via LFTP..."
        sudo apt-get update && sudo apt-get install -y lftp

        lftp -c "
        set ftp:ssl-force true
        set ftp:ssl-protect-data true
        set ssl:verify-certificate no
        open -u ${{ secrets.USERFTP }},${{ secrets.PASSWORDFTP }} ${{ secrets.FTPSERVER }}:${{ secrets.FTPPORT }}
        cd ${{ secrets.FTP_REMOTE_DIR }}
        mirror -R -v --exclude='^\.git' --exclude='^\.github' --exclude='README\.md' --exclude='deploy-prod\.sh' --exclude='ftp_batch\.txt' . .
        bye
        "