name: Deploy to server via SCP

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Test SSH connection
      run: |
        echo "Testing SSH connection..."
        mkdir -p ~/.ssh
        chmod 700 ~/.ssh
        ssh-keyscan -H ${{ secrets.SFTP_HOST }} >> ~/.ssh/known_hosts
        chmod 600 ~/.ssh/known_hosts
        echo "SSH host key added to known_hosts"

    - name: Deploy to server
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.SFTP_HOST }}
        port: ${{ secrets.SFTP_PORT }}
        username: ${{ secrets.SFTP_USERNAME }}
        password: ${{ secrets.SFTP_PASSWORD }}
        source: "."
        target: ${{ secrets.SFTP_REMOTE_DIR }}
        strip_components: 0
        overwrite: true
        rm: true
        timeout: 30s
      continue-on-error: true

    - name: Alternative deployment method
      if: failure()
      run: |
        echo "Primary deployment failed. Trying alternative method..."
        echo "You can manually deploy by uploading files to your server"
        echo "Required secrets:"
        echo "- SFTP_HOST: ${{ secrets.SFTP_HOST }}"
        echo "- SFTP_USERNAME: ${{ secrets.SFTP_USERNAME }}"
        echo "- Target directory: ${{ secrets.SFTP_REMOTE_DIR }}"
        echo "- Correct path should be: /home/toyarik/psychodiagnostic.online/www"
        echo ""
        echo "Manual deployment steps:"
        echo "1. Download the latest build from GitHub Actions artifacts"
        echo "2. Upload files to your server via FTP/SFTP"
        echo "3. Ensure config.php is created with correct credentials"