name: Deploy to server via SFTP

on:
  push:
    branches: ["main"]
    paths-ignore:
      - ".github/**"
      - "README.md"
  workflow_dispatch: {}

jobs:
  deploy:
    name: Upload site files to hosting
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Upload via SFTP
        uses: wlixcc/SFTP-Deploy-Action@v1.2.6
        with:
          server: ${{ secrets.SFTP_HOST }}
          port: ${{ secrets.SFTP_PORT }}
          username: ${{ secrets.SFTP_USERNAME }}
          password: ${{ secrets.SFTP_PASSWORD }}
          local_path: './'
          remote_path: ${{ secrets.SFTP_REMOTE_DIR }}
          sftpArgs: "-o ConnectTimeout=10"
          exclude: "**/.git*,**/.github/**,**/.DS_Store,**/node_modules/**,psychodiagnostic-site.zip"


