name: Deploy to Staging (staging.psychodiagnostic.online)

on:
  push:
    branches: [ staging ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: staging
      url: https://staging.psychodiagnostic.online
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy to Staging via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER_STAGING }}
          username: ${{ secrets.FTP_USER_STAGING }}
          password: ${{ secrets.FTP_PASS_STAGING }}
          protocol: ftp
          server-dir: ${{ secrets.FTP_DIR_STAGING || '/' }}
          local-dir: ./
          exclude: |
            **/.git*
            **/.github/**
            **/.DS_Store
            README.md
            **/deploy-prod.sh
            **/ftp_batch.txt
          log-level: minimal

