name: Deploy to server via SCP

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Test SSH connection
      run: |
        echo "Testing SSH connection..."
        mkdir -p ~/.ssh
        chmod 700 ~/.ssh
        ssh-keyscan -H ${{ secrets.SFTP_HOST }} >> ~/.ssh/known_hosts
        chmod 600 ~/.ssh/known_hosts
        echo "SSH host key added to known_hosts"

    - name: Deploy to server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SFTP_HOST }}
        port: ${{ secrets.SFTP_PORT }}
        username: ${{ secrets.SFTP_USERNAME }}
        password: ${{ secrets.SFTP_PASSWORD }}
        source: "."
        target: ${{ secrets.SFTP_REMOTE_DIR }}
        strip_components: 0
        overwrite: true
        rm: true
        timeout: 30s
        debug: true

    - name: Create config.php on server
      run: |
        echo "Creating config.php on server..."
        ssh -o StrictHostKeyChecking=no -p ${{ secrets.SFTP_PORT }} ${{ secrets.SFTP_USERNAME }}@${{ secrets.SFTP_HOST }} << 'EOF'
        cd ${{ secrets.SFTP_REMOTE_DIR }}
        cat > config.php << 'EOL'
        <?php
        return [
          'host' => 'mail.adm.tools',
          'port' => 587,
          'secure' => 'tls',
          'username' => 'info@psychodiagnostic.online',
          'password' => '${{ secrets.SMTP_PASSWORD }}',
          'from_email' => 'info@psychodiagnostic.online',
          'from_name' => 'PsychoDiagnostic'
        ];
        EOL
        echo "config.php created successfully"
        ls -la config.php
        EOF

    - name: Alternative deployment method
      if: failure()
      run: |
        echo "Deployment failed. Manual steps:"
        echo "1. Upload files to: ${{ secrets.SFTP_REMOTE_DIR }}"
        echo "2. Create config.php on server with SMTP credentials"
        echo "3. Test contact form functionality"