name: Deploy to server via SSH (rsync)

on:
  push:
    branches: ["main"]
    paths-ignore:
      - ".github/**"
      - "README.md"
  workflow_dispatch: {}

jobs:
  deploy:
    name: Upload site files to hosting
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Prepare SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -p "${{ secrets.SFTP_PORT }}" -t rsa "${{ secrets.SFTP_HOST }}" >> ~/.ssh/known_hosts

      - name: Upload via rsync over SSH
        run: |
          rsync -az --delete \
            --exclude ".git*" \
            --exclude ".github/" \
            --exclude "**/.DS_Store" \
            --exclude "**/node_modules/**" \
            --exclude "psychodiagnostic-site.zip" \
            -e "ssh -i ~/.ssh/id_ed25519 -p ${{ secrets.SFTP_PORT }} -o StrictHostKeyChecking=yes" \
            ./ ${{ secrets.SFTP_USERNAME }}@${{ secrets.SFTP_HOST }}:${{ secrets.SFTP_REMOTE_DIR }}


