name: Deploy to Production via FTP

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      confirm_deployment:
        description: 'Type "deploy" to confirm production deployment'
        required: true
        default: 'deploy'

jobs:
  deploy-ftp:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch' && github.event.inputs.confirm_deployment == 'deploy' || github.event_name == 'push'

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Test FTP connection
      run: |
        echo "Testing FTP connection..."
        echo "Server: ${{ secrets.FTPSERVER }}"
        echo "Port: ${{ secrets.FTPPORT }}"
        echo "Username: ${{ secrets.USERFTP }}"
        echo "Remote dir: ${{ secrets.FTP_REMOTE_DIR }}"
        # Test basic FTP connection
        timeout 10 bash -c "</dev/tcp/${{ secrets.FTPSERVER }}/${{ secrets.FTPPORT }}" && echo "✅ Port is open" || echo "❌ Port is closed or unreachable"

    - name: Deploy via FTPS
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTPSERVER }}
        username: ${{ secrets.USERFTP }}
        password: ${{ secrets.PASSWORDFTP }}
        server-dir: ${{ secrets.FTP_REMOTE_DIR }}
        port: ${{ secrets.FTPPORT }}
        protocol: ftps
        exclude: |
          **/.git*
          **/.github*
          **/README.md
          **/deploy-prod.sh
          **/ftp_batch.txt
        timeout: 60
        log-level: verbose