name: Deploy to Production (psychodiagnostic.online)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://psychodiagnostic.online
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy to Production via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER_PROD }}
          username: ${{ secrets.FTP_USER_PROD }}
          password: ${{ secrets.FTP_PASS_PROD }}
          protocol: ftp
          server-dir: ${{ secrets.FTP_DIR_PROD || '/' }}
          local-dir: ./
          exclude: |
            **/.git*
            **/.github/**
            **/.DS_Store
            README.md
            **/deploy-prod.sh
            **/ftp_batch.txt
          timeout: 120
          log-level: minimal