name: Deploy to server via SFTP

on:
  push:
    branches: ["main"]
    paths-ignore:
      - ".github/**"
      - "README.md"
  workflow_dispatch: {}

jobs:
  deploy:
    name: Upload site files to hosting
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Upload via SFTP
        uses: wangyucode/sftp-upload-action@v2
        with:
          host: ${{ secrets.SFTP_HOST }}
          port: ${{ secrets.SFTP_PORT }}
          username: ${{ secrets.SFTP_USERNAME }}
          password: ${{ secrets.SFTP_PASSWORD }}
          localDir: ./
          remoteDir: ${{ secrets.SFTP_REMOTE_DIR }}
          dryRun: false
          forceUpload: true
          exclude: .git*,.github/**,**/.DS_Store,**/node_modules/**,psychodiagnostic-site.zip


